cxx_compiler_version:          # [osx]
  # need to downgrade on osx due to a bug that breaks the test suite
  - 10                         # [osx]

c_compiler:                    # [win]
- vs2019                       # [win]
cxx_compiler:                  # [win]
- vs2019                       # [win]
